version: "3.9"
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env-prod
    ports:
      - "27017:27017"
    expose:
      - 27017

  psutech_etis_service:
    build:
      dockerfile: Dockerfile
    container_name: psutech_etis_service
    env_file:
      - .env-prod
    depends_on:
      - mongo
    ports:
      - "8010:8010"

volumes:
  mongo_data:
    driver: local